# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

loader_version=0.19.3
modmenu_version=7.2.2

# Mod Properties
mod_version=1.0.0
debug_version=4.2.0
maven_group=com.mormkillen
archives_base_name=speed-chromatic-aberration
mappings_kind=yarn

minecraft_version=26.1.2
yarn_mappings=
fabric_version=0.155.2+26.1.2
loom_version=1.15.5
java_release=25
java_toolchain=25
mc_tag=26.1.2
minecraft_dep=>=26.1 <26.2
java_dep=>=25
mappings_kind=mojmap
modmenu_version=21.0.0-alpha.1
fabric.loom.disableObfuscation=true
