# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

loader_version=0.19.3
modmenu_version=7.2.2

# Mod Properties
mod_version=1.0.0
debug_version=4.2.0
maven_group=com.mormkillen
archives_base_name=speed-chromatic-aberration
mappings_kind=yarn

minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
fabric_version=0.114.1+1.21.3
loom_version=1.15.5
java_release=21
java_toolchain=21
mc_tag=1.21.3
minecraft_dep=>=1.21.2 <1.21.4
java_dep=>=21
